/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Tesla Account User (Usually your Mailaddress)": {
        "en": "Tesla Account User (Usually your Mailaddress)",
        "de": "Tesla Benutzername (normalerweise Ihre E-Mail)",
        "ru": "Пользователь учетной записи Tesla (обычно ваш email)",
        "pt": "Usuário da conta Tesla (geralmente o seu endereço de email)",
        "nl": "Tesla-accountgebruiker (meestal uw e-mailadres)",
        "fr": "Compte utilisateur Tesla (généralement votre adresse mail)",
        "it": "Utente dell'account Tesla (di solito il tuo indirizzo di posta)",
        "es": "Usuario de la cuenta de Tesla (generalmente su dirección de correo electrónico)",
        "pl": "Użytkownik konta Tesla (zazwyczaj adres pocztowy)",
        "zh-cn": "Tesla帐户用户（通常是您的邮件地址）"
    },
    "Tesla Password": {
        "en": "Tesla Password",
        "de": "Tesla Passwort",
        "ru": "Тесла Пароль",
        "pt": "Senha Tesla",
        "nl": "Tesla-wachtwoord",
        "fr": "Tesla Mot de passe",
        "it": "Tesla Password",
        "es": "Contraseña de Tesla",
        "pl": "Hasło Tesli",
        "zh-cn": "特斯拉密码"
    },
    "Smart": {
        "en": "Smart",
        "de": "Smart",
        "ru": "Smart",
        "pt": "Inteligente",
        "nl": "Slim",
        "fr": "Intelligent",
        "it": "Inteligente",
        "es": "Inteligente",
        "pl": "Mądry",
        "zh-cn": "聪明"
    },
    "Aggressive": {
        "en": "Aggressive",
        "de": "Aggressiv",
        "ru": "Агрессивный",
        "pt": "Agressivo",
        "nl": "Agressief",
        "fr": "Agressif",
        "it": "Aggressivo",
        "es": "Agresivo",
        "pl": "Agresywny",
        "zh-cn": "好斗的"
    },
    "Temperate": {
        "en": "Temperate",
        "de": "Zurückhaltend",
        "ru": "Умеренный",
        "pt": "Temperado",
        "nl": "Gematigd",
        "fr": "Tempéré",
        "it": "Temperato",
        "es": "Templado",
        "pl": "Umiarkowany",
        "zh-cn": "温和的"
    },
    "Off": {
        "en": "Off",
        "de": "Aus",
        "ru": "Выкл",
        "pt": "Fora",
        "nl": "Uit",
        "fr": "De",
        "it": "via",
        "es": "Apagado",
        "pl": "Poza",
        "zh-cn": "关"
    },
    "Refresh Rate": {
        "en": "Refresh Rate",
        "de": "Aktualisierungsrate",
        "ru": "Частота обновления",
        "pt": "Taxa de atualização",
        "nl": "Verniewings snelheid",
        "fr": "Fréquence de rafraîchissement",
        "it": "Frequenza di aggiornamento",
        "es": "Frecuencia de actualización",
        "pl": "Częstotliwość odświeżania",
        "zh-cn": "刷新率"
    },
    "Save Credentials": {
        "en": "Save Credentials",
        "de": "Anmeldeinformationen speichern",
        "ru": "Сохранить учетные данные",
        "pt": "Salvar credenciais",
        "nl": "Referenties opslaan",
        "fr": "Enregistrer les informations d'identification",
        "it": "Salva credenziali",
        "es": "Guardar credenciales",
        "pl": "Zapisz poświadczenia",
        "zh-cn": "保存凭证"
    },
    "Get Token": {
        "en": "Get Token",
        "de": "Token holen",
        "ru": "Получить токен",
        "pt": "Obter token",
        "nl": "Ontvang een token",
        "fr": "Obtenir un jeton",
        "it": "Ottieni token",
        "es": "Obtener token",
        "pl": "Zdobądź Token",
        "zh-cn": "获取令牌"
    },
    "Token": {
        "en": "Token",
        "de": "Token",
        "ru": "Токен",
        "pt": "Símbolo",
        "nl": "blijk",
        "fr": "Jeton",
        "it": "Gettone",
        "es": "Simbólico",
        "pl": "Znak",
        "zh-cn": "代币"
    },
    "Refresh Token": {
        "en": "Refresh Token",
        "de": "Aktualisierungs-Token",
        "ru": "Refresh Token",
        "pt": "Atualizar token",
        "nl": "Token vernieuwen",
        "fr": "Refresh Token",
        "it": "Aggiorna token",
        "es": "Actualizar token",
        "pl": "Odśwież token",
        "zh-cn": "刷新令牌"
    },
    "Expires on": {
        "en": "Expires on",
        "de": "Läuft ab am",
        "ru": "Годен до",
        "pt": "Expira em",
        "nl": "Verloopt op",
        "fr": "Expire le",
        "it": "Scade il",
        "es": "Expira el",
        "pl": "Wygasa w dniu",
        "zh-cn": "到期"
    },
    "Select your Car": {
        "en": "Select your Car",
        "de": "Wählen Sie Ihr Auto",
        "ru": "Выберите свой автомобиль",
        "pt": "Selecione seu carro",
        "nl": "Selecteer uw auto",
        "fr": "Sélectionnez votre voiture",
        "it": "Seleziona la tua auto",
        "es": "Selecciona tu auto",
        "pl": "Wybierz swój samochód",
        "zh-cn": "选择你的车"
    },
    "Manually enter Token": {
        "en": "Manually enter Token",
        "de": "Token manuell eingeben",
        "ru": "Ввести токен вручную",
        "pt": "Insira o token manualmente",
        "nl": "Token handmatig invoeren",
        "fr": "Entrer manuellement le jeton",
        "it": "Inserisci manualmente il token",
        "es": "Ingrese el token manualmente",
        "pl": "Ręcznie wprowadź token",
        "zh-cn": "手动输入Token"
    },
    "Get Vehicles": {
        "en": "Get Vehicles",
        "de": "Fahrzeuge holen",
        "ru": "Получить автомобили",
        "pt": "Obter veículos",
        "nl": "Voertuigen ophalen",
        "fr": "Obtenir des véhicules",
        "it": "Ottieni veicoli",
        "es": "Obtener vehículos",
        "pl": "Zdobądź pojazdy",
        "zh-cn": "获取车辆"
    },
    "You have to get a Token before storing!": {
        "en": "You have to get a Token before storing!",
        "de": "Sie müssen ein Token holen, bevor sie speichern können!",
        "ru": "Вы должны получить токен перед сохранением!",
        "pt": "Você precisa obter um token antes de armazenar!",
        "nl": "Je moet een teken krijgen voordat je het opbergt!",
        "fr": "Vous devez obtenir un jeton avant de le stocker!",
        "it": "Devi ottenere un token prima di archiviarlo!",
        "es": "¡Tienes que conseguir un token antes de guardarlo!",
        "pl": "Przed przechowaniem musisz zdobyć token!",
        "zh-cn": "您必须先获得令牌，然后才能存储！"
    },
    "Please start the Adapter first": {
        "en": "Please start the Adapter first",
        "de": "Bitte starten Sie zuerst den Adapter",
        "ru": "Пожалуйста, сначала запустите адаптер",
        "pt": "Por favor, inicie o adaptador primeiro",
        "nl": "Start eerst de adapter",
        "fr": "S'il vous plaît commencer par l'adaptateur",
        "it": "Si prega di avviare prima l'adattatore",
        "es": "Por favor, inicie el adaptador primero",
        "pl": "Najpierw uruchom adapter",
        "zh-cn": "请先启动适配器"
    },
    "Save not possible, there is no vehicle selected.": {
        "en": "Save not possible, there is no vehicle selected.",
        "de": "Speichern nicht möglich, es ist kein Fahrzeug ausgewählt.",
        "ru": "Сохранить невозможно, автомобиль не выбран.",
        "pt": "Não é possível salvar, não há nenhum veículo selecionado.",
        "nl": "Opslaan niet mogelijk, er is geen voertuig geselecteerd.",
        "fr": "Sauvegarde impossible, aucun véhicule n'est sélectionné.",
        "it": "Salvataggio non possibile, nessun veicolo selezionato.",
        "es": "Guardar no es posible, no hay ningún vehículo seleccionado.",
        "pl": "Zapisywanie niemożliwe, nie wybrano pojazdu.",
        "zh-cn": "无法保存，没有选择车辆。"
    },
    "Your token is too short": {
        "en": "Your token is too short",
        "de": "Ihr Token ist zu kurz",
        "ru": "Ваш токен слишком короткий",
        "pt": "Seu token é muito curto",
        "nl": "Je token is te kort",
        "fr": "Votre jeton est trop court",
        "it": "Il tuo token è troppo corto",
        "es": "Tu ficha es demasiado corta",
        "pl": "Twój token jest za krótki",
        "zh-cn": "你的令牌太短"
    },
    "Could not get any vehicle": {
        "en": "Could not get any vehicle",
        "de": "Konnte kein Fahrzeug bekommen",
        "ru": "Не удалось получить автомобиль",
        "pt": "Não foi possível obter nenhum veículo",
        "nl": "Kon geen voertuig krijgen",
        "fr": "Impossible d'obtenir un véhicule",
        "it": "Non è stato possibile ottenere alcun veicolo",
        "es": "No se pudo conseguir ningún vehículo",
        "pl": "Nie udało się zdobyć żadnego pojazdu",
        "zh-cn": "无法获得任何车辆"
    },
    "explain_manual_entry": {
        "en": "If you don't get an answer from Tesla, there is most likely a change tesla made the library does not yet support.<br />\nTo still be able to use it, you can enter the token manually.",
        "de": "Wenn Sie keine Antwort von Tesla erhalten, gibt es höchstwahrscheinlich eine Änderung, die Tesla vorgenommen hat, die die Bibliothek noch nicht unterstützt.<br />\nUm ihn trotzdem nutzen zu können, können Sie den Token manuell eingeben.",
        "ru": "Если вы не получили ответа от Tesla, скорее всего, Tesla внесла изменение, которое библиотека еще не поддерживает.<br />\nЧтобы по-прежнему иметь возможность использовать его, вы можете ввести токен вручную.",
        "pt": "Se você não obtiver uma resposta do Tesla, provavelmente há uma alteração que o Tesla tornou a biblioteca ainda não compatível.<br />\nPara ainda ser capaz de usá-lo, você pode inserir o token manualmente.",
        "nl": "Als je geen antwoord krijgt van Tesla, is er hoogstwaarschijnlijk een wijziging aangebracht die de bibliotheek nog niet ondersteunt.<br />\nOm het toch te kunnen gebruiken, kunt u het token handmatig invoeren.",
        "fr": "Si vous n'obtenez pas de réponse de Tesla, il y a très probablement un changement que Tesla a fait que la bibliothèque ne prend pas encore en charge.<br />\nPour pouvoir toujours l'utiliser, vous pouvez saisir le jeton manuellement.",
        "it": "Se non ricevi una risposta da Tesla, è molto probabile che ci sia una modifica apportata da Tesla che la libreria non supporta ancora.<br />\nPer poterlo ancora utilizzare, puoi inserire il token manualmente.",
        "es": "Si no recibe una respuesta de Tesla, lo más probable es que haya un cambio que Tesla hizo que la biblioteca aún no es compatible.<br />\nPara poder seguir utilizándolo, puede ingresar el token manualmente.",
        "pl": "Jeśli nie otrzymasz odpowiedzi od Tesli, najprawdopodobniej istnieje zmiana, którą tesla sprawiła, że biblioteka jeszcze nie obsługuje.<br />\nAby nadal móc z niego korzystać, możesz wprowadzić token ręcznie.",
        "zh-cn": "如果您没有从 Tesla 得到答复，很可能是 tesla 做出了库尚不支持的更改。<br />\n为了仍然能够使用它，您可以手动输入令牌。"
    }
};
